apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempback-backend
  labels:
    app: tempback
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempback
      tier: backend
  template:
    metadata:
      labels:
        app: tempback
        tier: backend
    spec:
      containers:
        - name: tempback
          image: lanero/examen:backTemp
          ports:
            - name: api-server
              containerPort: 5000
          env:
            - name: "FLASK_ENV"
              value: "development" 



