apiVersion: v1
kind: Service
metadata:
  name: balancerbackend # Aqui se le 
spec:
  type: LoadBalancer
  selector:
    app: tempback # Aqui va el nombre del contenedor
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000