apiVersion: v1
kind: Service
metadata:
  name: balancerfrontend # Aqui se le 
spec:
  type: LoadBalancer
  selector:
    app: tempfront # Aqui va el nombre del contenedor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3002