apiVersion: v1
kind: Service
metadata:
  name: my-lb-service # Aqui se le 
spec:
  type: LoadBalancer
  selector:
    app: mysql # Aqui va el nombre del contenedor
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306